import java.io.File;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.Scanner;

/*
* There are two text files, whose names are stored in two String variables, file1 and file2.
* Both text files have the same number of lines.
Write a sequence of statements that creates a new file whose name is generated by concatenating the names of the
* two text files (with a "-" in the middle) and whose contents is generated by merging the lines of the two files.
Thus, in the new file, the first line is the first line from the first file,
* the second line is the first line from the second file. The third line in the new file is the second line in the first file and the fourth line is the second line from the second file, and so on.
*
* */

public class DoubleFilePrinter {
    public static void main(String[] args) throws IOException {

        String file1 = "grocery.txt";
        String file2 = "read.txt";

        Scanner inputFile1 = new Scanner(new File(file1));
        Scanner inputFile2 = new Scanner(new File(file2));

        String newFileName = file1+"-"+file2;

        PrintWriter newFile = new PrintWriter(newFileName);

        while(inputFile1.hasNext() && inputFile2.hasNext()){
            newFile.println(inputFile1.nextLine());
            newFile.println(inputFile2.nextLine());
        }
        newFile.close();
    }
}
